export default {
     black: {
          primary: "#1e1e1e",
          primaryAccent: "#0e0e0e",
          primaryVariant: "#1c1c1c",
          secondary: "white",
          secondaryAccent: "#efefef",
          secondaryVariant: "#5f5f5f",
     },
     blue: {
          primary: "#1e1e5e",
          primaryAccent: "#0e0e4e",
          primaryVariant: "#1c1c6c",
          secondary: "white",
          secondaryAccent: "#efefef",
          secondaryVariant: "#5f5f5f",
     },
     red: {
          primary: "#5c1c1c",
          primaryAccent: "#4c0c0c",
          primaryVariant: "#6c1c1c",
          secondary: "white",
          secondaryAccent: "#efefef",
          secondaryVariant: "#5f5f5f",
     },
     green: {
          primary: "#1e4e1e",
          primaryAccent: "#0e3e0e",
          primaryVariant: "#1c5c1c",
          secondary: "white",
          secondaryAccent: "#efefef",
          secondaryVariant: "#5f5f5f",
     },
     yellow: {
          primary: "#4e4e1e",
          primaryAccent: "#3e3e0e",
          primaryVariant: "#5c5c1c",
          secondary: "white",
          secondaryAccent: "#efefef",
          secondaryVariant: "#5f5f5f",
     },
     cyan: {
          primary: "#1e4e4e",
          primaryAccent: "#0e3e3e",
          primaryVariant: "#1c5c5c",
          secondary: "white",
          secondaryAccent: "#efefef",
          secondaryVariant: "#5f5f5f",
     },
     purple: {
          primary: "#301934",
          primaryAccent: "#251429",
          primaryVariant: "#352439",
          secondary: "white",
          secondaryAccent: "#efefef",
          secondaryVariant: "#5f5f5f",
     },
};
